// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/**
 * @title IVerifier
 * @notice Interface for a Verifier contract. 
 * @dev The verifier contract is responsible for verifying zk-SNARK proofs. It is generated by snarkjs for the composite-check circuit used in the challenge.
 */
interface IVerifier {
    function verifyProof(
        uint256[2] calldata _pA,
        uint256[2][2] calldata _pB,
        uint256[2] calldata _pC,
        uint256[2] calldata _pubSignals
    ) external view returns (bool);
}
